---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Mahadevan Subramanian"
keywords:    "SinglePaged, jekyll, template, github, blog, single page"
description: "Personal homepage"
source_link: "https://github.com/t413/SinglePaged"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: # UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#566167'
  white:     '#f8f8f8'
  blue:      '#5c8bbc'
  green:     '#43a44c'
  purple:    '#77219a'
  orange:    '#9a2168'
  turquoise: '#34b6b5'

kramdown:
  auto_ids:  false

